### ISSUE TITLE
Upload fails due to API changes

### ISSUE THREAD

**Issue by mpolla** [misev/garmin-upload#1]
> $ ./garmin-upload.py 12345.gpx
Traceback (most recent call last):
  File "./garmin-upload.py", line 133, in <module>
    cookies = signin(username, password)
  File "./garmin-upload.py", line 61, in signin
    data["lt"] = re.search("name=\"lt\"\s+value=\"([^\"]+)\"", pre_resp.text).groups(1)[0]
AttributeError: 'NoneType' object has no attribute 'groups'

I assume this is due to API changes at Garmin. The response also says
> Your browser is no longer supported on Garmin Connect.

**Comment by misev** [comment]
Unfortunately I haven't used it with Garmin Connect for quite some time, only Strava nowadays.

**Comment by misev** [comment]
Seems like there is an up-to-date alternative: https://github.com/La0/garmin-uploader
